# Generated by Django 3.0.4 on 2022-09-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_group',
            field=models.CharField(max_length=255, null=True, verbose_name='notification_group'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.CharField(max_length=30),
        ),
    ]
