# Generated by Django 3.0.4 on 2022-09-29 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_auto_20220906_1434'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
