# Generated by Django 3.0.4 on 2022-09-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('service_app', '0003_delete_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=35)),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('message', models.TextField()),
                ('url', models.SlugField()),
                ('email', models.EmailField(max_length=255, null=True)),
                ('notification_group', models.CharField(max_length=255, null=True, verbose_name='notification_group')),
            ],
        ),
    ]
